#!/bin/bash
rm -rf install

pkg update && pkg upgrade -y

ARCH=$(uname -m)

if [[ "$ARCH" == "aarch64" || "$ARCH" == "arm64" ]]; then
    DNSTT_CLIENT_URL="https://github.com/hahacrunchyrollls/dnstt-client/raw/refs/heads/main/dnstt-client_arm64"
    DNSTT_URL="https://github.com/hahacrunchyrollls/dnstt-client/raw/refs/heads/main/client-0"
elif [[ "$ARCH" == "armv7l" || "$ARCH" == "armv7" ]]; then
    DNSTT_CLIENT_URL="https://github.com/hahacrunchyrollls/dnstt-client/raw/refs/heads/main/dnstt-client_armv7"
    DNSTT_URL="https://github.com/hahacrunchyrollls/dnstt-client/raw/refs/heads/main/client-1"
else
    echo "Unsupported architecture: $ARCH"
    exit 1
fi

curl -sLo "$PREFIX/bin/dnstt-client" "$DNSTT_CLIENT_URL"
chmod +x "$PREFIX/bin/dnstt-client"

curl -sLo "$PREFIX/bin/dnstt" "$DNSTT_URL"
chmod +x "$PREFIX/bin/dnstt"
mv "$PREFIX/bin/dnstt" "$PREFIX/bin/client"

YELLOW='\033[1;33m'
GREEN='\033[1;32m'
NC='\033[0m'

echo -e "${YELLOW}Press Enter to continue...${NC}"
read -p ""
echo -e "${GREEN}Ready! Type 'client' to start${NC}"
